//
// Generated by LLVM NVPTX Back-End
//

.version 3.2
.target sm_20, texmode_independent
.address_size 64

	// .globl	SYCL_struct_body_integrator // -- Begin function SYCL_struct_body_integrator
                                        // @SYCL_struct_body_integrator
.entry SYCL_struct_body_integrator(
	.param .u64 .ptr .global .align 16 SYCL_struct_body_integrator_param_0,
	.param .align 4 .b8 SYCL_struct_body_integrator_param_1[16],
	.param .align 4 .b8 SYCL_struct_body_integrator_param_2[16],
	.param .align 4 .b8 SYCL_struct_body_integrator_param_3[16],
	.param .u64 .ptr .global .align 16 SYCL_struct_body_integrator_param_4,
	.param .align 4 .b8 SYCL_struct_body_integrator_param_5[16],
	.param .align 4 .b8 SYCL_struct_body_integrator_param_6[16],
	.param .align 4 .b8 SYCL_struct_body_integrator_param_7[16],
	.param .u64 .ptr .global .align 16 SYCL_struct_body_integrator_param_8,
	.param .align 4 .b8 SYCL_struct_body_integrator_param_9[16],
	.param .align 4 .b8 SYCL_struct_body_integrator_param_10[16],
	.param .align 4 .b8 SYCL_struct_body_integrator_param_11[16],
	.param .u64 .ptr .shared .align 16 SYCL_struct_body_integrator_param_12,
	.param .align 4 .b8 SYCL_struct_body_integrator_param_13[16],
	.param .align 4 .b8 SYCL_struct_body_integrator_param_14[16],
	.param .align 4 .b8 SYCL_struct_body_integrator_param_15[16],
	.param .u64 SYCL_struct_body_integrator_param_16,
	.param .u32 SYCL_struct_body_integrator_param_17
)
{
	.reg .pred 	%p<5>;
	.reg .f32 	%f<80>;
	.reg .b32 	%r<19>;
	.reg .b64 	%rd<26>;

// %bb.0:
	ld.param.u64 	%rd11, [SYCL_struct_body_integrator_param_16];
	mov.u32 	%r9, %tid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r3, %ntid.x;
	mad.lo.s32 	%r11, %r3, %r10, %r9;
	cvt.u64.u32 	%rd2, %r11;
	setp.ge.u64 	%p1, %rd2, %rd11;
	@%p1 bra 	LBB0_8;
// %bb.1:
	ld.param.u32 	%r8, [SYCL_struct_body_integrator_param_17];
	ld.param.u64 	%rd9, [SYCL_struct_body_integrator_param_8];
	ld.param.u64 	%rd8, [SYCL_struct_body_integrator_param_4];
	ld.param.u64 	%rd7, [SYCL_struct_body_integrator_param_0];
	shl.b64 	%rd12, %rd2, 4;
	add.s64 	%rd13, %rd7, %rd12;
	ld.global.v4.f32 	{%f1, %f2, %f3, %f4}, [%rd13];
	setp.eq.s32 	%p2, %r8, 0;
	@%p2 bra 	LBB0_2;
// %bb.3:
	ld.param.u64 	%rd10, [SYCL_struct_body_integrator_param_12];
	ld.param.u32 	%r1, [SYCL_struct_body_integrator_param_15+4];
	ld.param.u32 	%r2, [SYCL_struct_body_integrator_param_15+8];
	cvt.u64.u32 	%rd1, %r9;
	cvt.u64.u32 	%rd3, %r3;
	mul.wide.s32 	%rd14, %r2, %r1;
	mul.lo.s64 	%rd15, %rd14, %rd1;
	shl.b64 	%rd16, %rd15, 4;
	add.s64 	%rd4, %rd10, %rd16;
	mov.f32 	%f74, 0f00000000;
	mov.u32 	%r17, 0;
	mov.u32 	%r15, 1597463007;
	mov.f32 	%f75, %f74;
	mov.f32 	%f76, %f74;
LBB0_4:                                 // =>This Loop Header: Depth=1
                                        //     Child Loop BB0_5 Depth 2
	cvt.u64.u32 	%rd17, %r17;
	mul.lo.s64 	%rd18, %rd17, %rd3;
	add.s64 	%rd19, %rd18, %rd1;
	shl.b64 	%rd20, %rd19, 4;
	add.s64 	%rd21, %rd7, %rd20;
	ld.global.v4.f32 	{%f29, %f30, %f31, %f32}, [%rd21];
	st.shared.v4.f32 	[%rd4], {%f29, %f30, %f31, %f32};
	bar.sync 	0;
	mov.u32 	%r18, %r3;
	mov.u64 	%rd25, %rd10;
LBB0_5:                                 //   Parent Loop BB0_4 Depth=1
                                        // =>  This Inner Loop Header: Depth=2
	ld.shared.v4.f32 	{%f33, %f34, %f35, %f36}, [%rd25];
	sub.rn.f32 	%f37, %f33, %f1;
	sub.rn.f32 	%f38, %f34, %f2;
	sub.rn.f32 	%f39, %f35, %f3;
	fma.rn.f32 	%f40, %f39, %f39, 0f358637BE;
	fma.rn.f32 	%f41, %f38, %f38, %f40;
	fma.rn.f32 	%f42, %f37, %f37, %f41;
	mul.rn.f32 	%f43, %f42, %f42;
	mul.rn.f32 	%f44, %f42, %f43;
	mul.rn.f32 	%f45, %f44, 0fBF000000;
	mov.b32 	%r13, %f44;
	shr.s32 	%r14, %r13, 1;
	sub.s32 	%r16, %r15, %r14;
	mov.b32 	%f46, %r16;
	mul.rn.f32 	%f47, %f45, %f46;
	mul.rn.f32 	%f48, %f47, %f46;
	add.rn.f32 	%f49, %f48, 0f3FC00000;
	mul.rn.f32 	%f50, %f49, %f46;
	mul.rn.f32 	%f51, %f36, %f50;
	fma.rn.f32 	%f76, %f39, %f51, %f76;
	fma.rn.f32 	%f75, %f38, %f51, %f75;
	fma.rn.f32 	%f74, %f37, %f51, %f74;
	add.s64 	%rd25, %rd25, 16;
	add.s32 	%r18, %r18, -1;
	setp.eq.s32 	%p3, %r18, 0;
	@%p3 bra 	LBB0_6;
	bra.uni 	LBB0_5;
LBB0_6:                                 //   in Loop: Header=BB0_4 Depth=1
	bar.sync 	0;
	add.s32 	%r17, %r17, 1;
	setp.eq.s32 	%p4, %r17, %r8;
	@%p4 bra 	LBB0_7;
	bra.uni 	LBB0_4;
LBB0_2:
	mov.f32 	%f74, 0f00000000;
	mov.f32 	%f75, %f74;
	mov.f32 	%f76, %f74;
LBB0_7:
	add.s64 	%rd23, %rd9, %rd12;
	ld.global.v4.f32 	{%f52, %f53, %f54, %f55}, [%rd23];
	mul.rn.f32 	%f56, %f76, 0f3E4CCCCD;
	mul.rn.f32 	%f57, %f75, 0f3E4CCCCD;
	mul.rn.f32 	%f58, %f74, 0f3E4CCCCD;
	add.rn.f32 	%f59, %f52, %f58;
	add.rn.f32 	%f60, %f53, %f57;
	add.rn.f32 	%f61, %f54, %f56;
	mul.rn.f32 	%f62, %f61, 0f3F000000;
	mul.rn.f32 	%f63, %f60, 0f3F000000;
	mul.rn.f32 	%f64, %f59, 0f3F000000;
	mul.rn.f32 	%f65, %f64, 0f3E4CCCCD;
	mul.rn.f32 	%f66, %f63, 0f3E4CCCCD;
	mul.rn.f32 	%f67, %f62, 0f3E4CCCCD;
	add.rn.f32 	%f68, %f3, %f67;
	add.rn.f32 	%f69, %f2, %f66;
	add.rn.f32 	%f70, %f1, %f65;
	add.s64 	%rd24, %rd8, %rd12;
	st.global.v4.f32 	[%rd24], {%f70, %f69, %f68, %f4};
	st.global.v4.f32 	[%rd23], {%f64, %f63, %f62, %f55};
LBB0_8:
	ret;
}
                                        // -- End function

